<a href="https://colab.research.google.com/github/someshsingh22/CTE-Intro-To-Machine-Learning/blob/master/Week-1%20Getting%20Started/01_Introduction_to_Python%2CNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Python3 Programming Language

## Some programming background and Languages(own notes)

In [0]:
x = 1
y = 2
print("sum of x & y = ",x + y)
print("product of x & y = ",x * y)
print("Divide x by y = ",x / y)
print("Integert Divide x by y = ",x // y)
print("x to the power of y = ",x**y)

sum of x & y =  3
product of x & y =  2
Divide x by y =  0.5
Integert Divide x by y =  0
x to the power of y =  1


## Functions

In [0]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

In [0]:
def add_numbers(x, y):
    return x + y

k = add_numbers(1, 2) #the output of function is what is in front of return statement
k

3

<br>
`add_numbers` updated to take an optional 3rd parameter. Using `print` allows printing of multiple expressions within a single cell.

In [0]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


<br>
`add_numbers` updated to take an optional flag parameter.

In [0]:
def add_numbers(x, y, z=None, flag=False):
    if (flag): #if statements , elif , and else statements
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True)) #or be called as
print("=======")
print(add_numbers(1, 2, None, True)) #or be called as
print("=======")
print(add_numbers(1, 2, flag = True, z = None))

Flag is true!
3
Flag is true!
3
Flag is true!
3


<br>
Keyword arguments only after Non_Keyword arguements

In [0]:
def add_numbers(x, z=None,y, flag=False): #Throws error.
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z

SyntaxError: non-default argument follows default argument (<ipython-input-6-947802767eb5>, line 1)

<br>
Assign function `add_numbers` to variable `a`.

In [0]:
def add_numbers(x,y):
    return x+y

a = add_numbers #Assigned the function ,but not called
a(1,2) #Now called

3

<br>
Any number of non-keyword arguements to `add_numbers`

In [0]:
def add_number(*args):
    summer = 0
    #print(type(args))
    for elems in args:
        summer = summer + elems
    return summer
print(add_number(1,2,3,4,5))

15


<br>
Similarly any number of keyword arguements to `add_numbers` but most follow non_keyword arguments (Note there can be only keyword arguements)

In [0]:
def add_number(*args, **kwargs):
    summer1 = 0
    summer2 = 0
    print(type(args)) #A tuple will come back later
    print(type(kwargs)) # A dict will come back later
    for elems in args:
        summer1 = summer1 + elems
    for items in kwargs:
        summer2 = summer2 + kwargs[items]
    return summer1, summer2
print(add_number(a=2, b=3, c=3)) #Returning a tuple

<class 'tuple'>
<class 'dict'>
(0, 8)


<br>
# The Python Programming Language: Types and Sequences

<br>
Use `type` to return the object's type.

### String : Collection of Characters, Characters are stored as integers (Python Uses Unicode to store strings)

In [0]:
type('This is a string') 

str

In [0]:
ord('A') #UTF-8 / Ascii value of character A. Read further on ascii and utf-8

65

In [0]:
type(None)

NoneType

In [0]:
type(1)

int

In [0]:
type(1.0)

float

In [0]:
type(add_numbers)

function

<br>
``Tuples`` are collection of Python data types(int,char,str,float).
No alteration allowed.
Useful for things you want to remain unchanged throughout code.

In [0]:
x = (1, 'a', 2, 'b') #initiated by ()
type(x)

tuple

In [0]:
print(id(x)) #To check uniqueness
y = x
print(id(y))

4596950216
4596950216


<br>
``Lists`` on the other hand are the alterable version on ``Tuples``.Super-Powerful alterations though

In [0]:
x = [1, 'a', 2, 'b'] #[]
type(x)

list

In [0]:
y = x #Creates a reference to x

In [0]:
print(id(x))
print(id(y))

4596950216
4596950216


<br>
Use `append` to append an object to a list.

In [0]:
print(x.append(3.3)) #Is append is a function that changes x in memory but returns None
print(x)

None
[1, 'a', 2, 'b', 3.3, 3.3]


<br>
This is an example of how to loop through each item in the list.

In [0]:
for item in x:
    print(item)

1
a
2
b
3.3


In [0]:
for item in x:
    print(item, " ", end = "")

1  a  2  b  3.3  

<br>
Or using the indexing operator:

In [0]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
a
2
b
3.3


<br>
Use `+` to concatenate lists.

In [0]:
x = [1,2] + [3,4]

[1, 2, 3, 4]

In [0]:
x = [1,2]
print(id(x))
y = x + [3,4] #This alteration happens in a seperate memory location. 
print(id(y))

4596950472
4596932936


<br>
Use `*` to repeat lists.

In [0]:
[1]*3

[1, 1, 1]

<br>
Use the `in` operator to check if something is inside a list.

In [0]:
1 in [1, 2, 3]

True

### String Slicing
<br>
Now let's look at strings. Use bracket notation to slice a string.

In [0]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #[first_element_index_to_include:first_element_index_to_exclude]
print(x[0:2]) #[first_element_index_to_include:first_element_index_to_exclude]

T
T
Th


<br>
This will return the last element of the string.

In [0]:
x[-1]

'g'

<br>
This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [0]:
x[-4:-2]

'ri'

In [0]:
x[-4:-6] #Exclusion rule overrides inclusion.

''

In [0]:
x[-4:-6:-1]

'rt'

In [0]:
x[-1::-1] #Inverto

'gnirts a si sihT'

<br>
This is a slice from the beginning of the string and stopping before the 3rd element.

In [0]:
x[:3]

'Thi'

<br>
And this is a slice starting from the 3rd element of the string and going all the way to the end.

In [0]:
x[3:]

's is a string'

In [0]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)


Christopher Brooks
ChristopherChristopherChristopher
True


<br>
`split` is a function that returns a list of all the words in a string, or a list split on a specific character.

In [0]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ') # [0] selects the first element of the list
lastname = 'Christopher Arthur;Hansen Brooks'.split(';') # [-1] selects the last element of the list
print(firstname)
print(lastname)

['Christopher', 'Arthur', 'Hansen', 'Brooks']
['Christopher Arthur', 'Hansen Brooks']


<br>
Make sure you convert objects to strings before concatenating.

In [0]:
'Chris' + 2

TypeError: Can't convert 'int' object to str implicitly

In [0]:
'Chris' + str(2) #or '2'

'Chris2'

<br>
``Dictionaries`` are too good. More interesting in reading material. Key left, value to the right, Key cant be repeated

In [0]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator

'brooksch@umich.edu'

In [0]:
x['Kevyn Collins-Thompson'] = None #Add a key-value pair
x['Kevyn Collins-Thompson']

<br>
Iterate over all of the keys:

In [0]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


<br>
Iterate over all of the values:

In [0]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


<br>
Iterate over all of the items in the list:

In [0]:
for name, email in x.items(): #returns tuples at each round of loop
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


<br>
You can unpack a sequence into different variables:

In [0]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [0]:
fname

'Christopher'

In [0]:
lname

'Brooks'

<br>
Make sure the number of values you are unpacking matches the number of variables being assigned.

In [0]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email = x

ValueError: too many values to unpack (expected 3)

<br>
# The Python Programming Language: More on Strings

<br>
Python has a built in method for convenient string formatting.

In [0]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


<br>
# Reading and Writing CSV files (we dont use this but keep this in mind)

<br>
Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

In [0]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

<br>
`csv.Dictreader` has read in each row of our csv file as a dictionary. `len` shows that our list is comprised of 234 dictionaries.

In [0]:
len(mpg)

234

<br>
`keys` gives us the column names of our csv.

In [0]:
mpg[2]['cty']

'20'

<br>
This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.

In [0]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

<br>
Similarly this is how to find the average hwy fuel economy across all cars.

In [0]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

<br>
Use `set` to return the unique values for the number of cylinders the cars in our dataset have.

In [0]:
cylinders = set(d['cyl'] for d in mpg) #Removes repeated values
cylinders

{'4', '5', '6', '8'}

<br>
Here's a more complex example where we are grouping the item_id by same shop_id

In [0]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0]) #Wait for lambda
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

<br>
Use `set` to return the unique values for the class types in our dataset.

In [0]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

<br>
And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

In [0]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1]) #Wait for lambda
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

<br>
# The Python Programming Language: Dates and Times

In [0]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [0]:
tm.time()

1532071016.81

<br>
Convert the timestamp to datetime.

In [0]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2018, 7, 20, 12, 47, 32, 822517)

In [0]:
type(dtnow) #Is an object of class datetime

datetime.datetime

<br>
Handy datetime attributes:

In [0]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2016, 10, 26, 13, 42, 18)

<br>
`timedelta` is a duration expressing the difference between two dates.

In [0]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(100)

<br>
`date.today` returns the current local date.

In [0]:
today = dt.date.today()
today

datetime.date(2018, 7, 20)

In [0]:
today - delta # the date 100 days ago

datetime.date(2018, 4, 11)

In [0]:
today > today-delta # compare dates

True

<br>
# The Python Programming Language: Objects and map()

<br>
An example of a class in python:

### Python has almost everything as an object. Even functions!!

In [0]:
class Person:
    department = 'School of Information' #a class variable(common to all objects of the class Person)
    def __init__(self,*args,**kwargs):
        pass

    def set_name(self, new_name): #a method (function of an object nothing fancy)
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [0]:
person1 = Person() #Initiaites the init function. With first arguement as itself(person1)

In [0]:
person1.set_name('Christopher Brooks')
person1.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person1.name, person1.location, person1.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


<br>
Here's an example of mapping the `min` function between two lists.

In [0]:
??map

In [0]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest #Returns object of class map, is iteratable

<br>
Now let's iterate through the map object to see the values.

In [0]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [0]:
my_function = lambda a, b, c : a + b #Function with name lamda taking arguement a,b,c returning a + b

### Why use lambda?? Short , Crisp and Very handy when dealing with data wrangling when we need to perform real simple and quick tasks. You'll get used to it

In [0]:
my_function(1, 2, 3) #Calling the function

3

### Try writing this as a usual function. And see for yourself how concise this is.

In [0]:
mult = filter(lambda x: x % 3 == 0, [1, 2, 3, 4, 5, 6, 7, 8, 9])

<br>
Let's iterate from 0 to 999 and return the even numbers.

In [0]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

<br>
Now the same thing but with list comprehension. Similar to lambda function this crisp and concise.
You can do all sorts of complex things with this. More fun in the assignment

In [0]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

<br>
# The Python Programming Language: Numerical Python (NumPy)

In [0]:
import numpy as np #Import numpy package and all its functionalities with the name as np. 

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [0]:
mylist = [1, 2, 3, "a"]
x = np.array(mylist) #. notation to access functions/ attributes from numpy package just like an object
x

array(['1', '2', '3', 'a'],
      dtype='<U21')

<br>
Or just pass in a list directly

In [0]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [0]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [0]:
m.shape

(2, 3)

<br>
`arange` returns evenly spaced values within a given interval.

In [0]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [0]:
id(n)

4737159616

<br>
`reshape` returns an array with the same data with a new shape.

In [0]:
n = n.reshape(3, 5) # reshape array to be 3x5, happens on a copy of n.
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [0]:
id(n)

4737101536

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [0]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

<br>
`resize` changes the shape and size of array in-place.

In [0]:
o.resize(3, 3) #no_need to do o = o.reshape(3,3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [0]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [0]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [0]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [0]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

<br>
Create an array using repeating list (or see `np.tile`)

In [0]:
??np.tile

In [0]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [0]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
#### Combining Arrays

In [0]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

<br>
Use `vstack` to stack arrays in sequence vertically (row wise).

In [0]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [0]:
np.vstack([p, 2*p]).shape

(4, 3)

<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [0]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [0]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [0]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[ 0.25  0.4   0.5 ]


In [0]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [0]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [0]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [0]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>
The shape of array `z` is `(2,3)` before transposing.

In [0]:
z.shape

(2, 3)

<br>
Use `.T` to get the transpose.

In [0]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>
The number of rows has swapped with the number of columns.

In [0]:
z.T.shape

(3, 2)

<br>
Use `.dtype` to see the data type of the elements in the array.

In [0]:
z.dtype

dtype('int64')

<br>
Use `.astype` to cast to a specific type.

In [0]:
z = z.astype('f')
z.dtype

dtype('float32')

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [0]:
a = np.array([-4, -2, 1, 3, 5])

In [0]:
a.sum()

3

In [0]:
a.max()

5

In [0]:
a.min()

-4

In [0]:
a.mean()

0.60

In [0]:
a.std()

3.26

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [0]:
a.argmax()

4

In [0]:
a.argmin()

0

<br>
## Indexing / Slicing

In [0]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [0]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [0]:
s[1:5]

array([ 1,  4,  9, 16])

<br>
Use negatives to count from the back.

In [0]:
s[-4:]

array([ 81, 100, 121, 144])

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [0]:
s[-5::-2]

array([64, 36, 16,  4,  0])

<br>
Let's look at a multidimensional array.

In [0]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Use bracket notation to slice: `array[row, column]`

In [0]:
r[2, 2]

14

<br>
And use : to select a range of rows or columns

In [0]:
r[3, 3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [0]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [0]:
r[-1, ::2]

array([30, 32, 34])

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [0]:
r[r > 30]

array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [0]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [0]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [0]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`r` has also been changed!

In [0]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [0]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Now when r_copy is modified, r will not be changed.

In [0]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [0]:
test = np.random.randint(0, 10, (4,3)) #Nothing is random its a game of seeds
test

array([[2, 6, 4],
       [8, 2, 0],
       [0, 3, 8],
       [3, 1, 4]])

<br>
Iterate by row:

In [0]:
for row in test:
    print(row)

[2 6 4]
[8 2 0]
[0 3 8]
[3 1 4]


<br>
Iterate by index:

In [0]:
for i in range(len(test)):
    print(test[i])

[2 6 4]
[8 2 0]
[0 3 8]
[3 1 4]


<br>
Iterate by row and index:

In [0]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [2 6 4]
row 1 is [8 2 0]
row 2 is [0 3 8]
row 3 is [3 1 4]


<br>
Use `zip` to iterate over multiple iterables.

In [0]:
test2 = test**2
test2

array([[ 4, 36, 16],
       [64,  4,  0],
       [ 0,  9, 64],
       [ 9,  1, 16]])

In [0]:
for i, j in zip(test, test2): #More uses on zip, later. Read_Docs
    print(i,'+',j,'=',i+j)

[2 6 4] + [ 4 36 16] = [ 6 42 20]
[8 2 0] + [64  4  0] = [72  6  0]
[0 3 8] + [ 0  9 64] = [ 0 12 72]
[3 1 4] + [ 9  1 16] = [12  2 20]
